### ISSUE TITLE
Automatic upgrade of JS dependencies

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/github-actions-ci-cd#10]
As maintainers, I want JS dependencies to automatically upgrade themselves across all repos

**Comment by sminnee** [comment]
One thing on this I would note - dependabot does a PR per package, whereas depfu can do a single PR for the whole update. That might be less hassle, given the rate of change of the NPM ecosystem...

**Comment by maxime-rainville** [comment]
Already done.
