### ISSUE TITLE
Disable matrix

### ISSUE THREAD

**Issue by jamsea** [silverstripe/github-actions-ci-cd#18]
Hi there,

We're starting a brand new SilverStripe project for a client this week and I'm setting up the CI/CD workflow. Since we control the server we're only targeting PHP 7.4. My questions are:

1. Is there a way to disable running the PHP 8 jobs currently?
2. Does it make sense to build on top of this workflow for a normal SilverStripe project or should I just build my own?

If there isn't a way to disable the matrix let me know if there's a particular way you'd want that feature implemented, and I'll make a pull request.

Thanks!

**Comment by emteknetnz** [comment]
Probably build your own, the CI here is a first cut and we'll release a new one in the next few months. The CI here is aimed at modules not projects. Copy pasting the code here could be a good start, though there's plenty here you probably can just delete

That said you can just use this if it works for you

To set your own matrix, set

```
with:
  default_jobs: |
```

To whatever you like, see https://github.com/silverstripe/github-actions-ci-cd/blob/740d9e2922d590113b5d18f6cdecaf99d0e0bc64/.github/workflows/ci.yml#L28
