### ISSUE TITLE
Generate matrix action

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/github-actions-ci-cd#33]
Our current GitHub actions set up will generate a matrix of builds to cover a variety of setup and test cases. (PHP8 on MySQL, PHP7.4 on PostgreSQL, etc). There's a process that automatically tries to generate this matrix based on the project set up. We need to make sure this matrix generation is fit for purpose.

Update emteknetnz/gha-generate-matrix action (will be ported over to silverstripe account)

### ACs
- [x] Dynamic detection of installer version to support older versions e.g. 4.9
- [x] Map of installer to php version
- [x] Multi-DB support - Postgres / PDO / MySQL 5.7 + 8.0
- [x] --prefer-lowest
- [x] There's a way to override the defaults
- [x] How to use Matrix generation is documented
- ~~Update [docs site](https://docs.silverstripe.org/en/4/getting_started/server_requirements/#database) - says mysql 5.6 is support (minimum we test is 5.7), postgres is community supported (though should be commercial if it's in matrix?), sql server + sqlite are not tested at all, should probably be removed~~ Covered in https://github.com/silverstripeltd/product-issues/issues/551

### PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10334
- https://github.com/silverstripe/silverstripe-userforms/pull/1149
- https://github.com/silverstripe/gha-generate-matrix/pull/1

**Comment by emteknetnz** [comment]
Example run https://github.com/emteknetnz/silverstripe-campaign-admin/actions/runs/2380795809

**Comment by ChloeSartorelli** [comment]
@emteknetnz Is there a PR somewhere to update the server requirements docss as per ACs?

**Comment by emteknetnz** [comment]
Nope - I've now split that one off to its own [issue](https://github.com/silverstripeltd/product-issues/issues/551) and removed the AC

It was more of a note of something I noticed while doing this work rather than an AC

**Comment by ChloeSartorelli** [comment]
PRs merged and ACs met.
