### ISSUE TITLE
Migrate dynamic2 ci.yml

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/github-actions-ci-cd#34]
Steve has been working on the next iteration of our GitHub actions set up. He's got a working prototype that needs to be folded back in.

### ACs
- [x] Tidy up workflow
- [x] Ensure it works with all use cases, e.g. framework, installer, kitchen-sink, recipe-*, userforms
- [x] Ensure that any new logic recently added to travis-shared is ported over
- [ ] Create 0.1 branch for 0.1.* releases
- [ ] Replace existing workflow with https://github.com/emteknetnz/github-actions-ci-cd/blob/dynamic2/.github/workflows/ci.yml
- [ ] Workflows shows be in root dir, not .github/workflows dir if possible e.g. silverstripe/github-actions-ci-cd/ci.yml
- [ ] ^ if this is possible, references to update-js-deps.yml workflow in modules should be updated at the same time

**Comment by emteknetnz** [comment]
Example run https://github.com/emteknetnz/silverstripe-campaign-admin/actions/runs/2380795809

**Comment by ChloeSartorelli** [comment]
@emteknetnz Can this be closed as a duplicate of #36?

**Comment by emteknetnz** [comment]
Yeah
