### ISSUE TITLE
Migrate emteknetnz gha actions

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/github-actions-ci-cd#36]
Create new repos on silverstripe account with emtpy readme only, then fork repos to emteknetnz, and create PRs with copy pasted contents from gha versions so they can all be peer reviewed

I'm thinking we should retain the gha- prefix instead of the github-actions- prefix, and also split the exsiting 'workflow_call' style github-actions-ci-ci repo to a pair of actions to be consistent:
- gha-ci
- gha-update-js (ditch the -deps suffix since it also does a build)

### ACs
- [x] gha-run-tests
- [x] gha-pull-request
- [x] gha-tag-release
- [x] gha-auto-tag 
- [x] gha-generate-matrix
- [x] gha-ci
- [x] gha-update-js
- [x] gha-keepalive
- [x] Update readme instructions for each so it's clear how to use them
- [x] Add auto-tag action to each workflow in each action
- [x] Update actions/workflows to use silverstripe @v1 versions
- [x] Tag release 1.0.0 of each module
- [x] Validate that errors systematically failed the build
- [x] Validate that pass string input variables and pull request title though env variables
- [x] Validate that Pin third party actions to specific shas works

### PRs
- [x] https://github.com/silverstripe/gha-auto-tag/pull/1
- [x] https://github.com/silverstripe/gha-generate-matrix/pull/1
- [x] https://github.com/silverstripe/gha-run-tests/pull/1
- [x] https://github.com/silverstripe/gha-ci/pull/1
- [x] https://github.com/silverstripe/gha-pull-request/pull/1
- [x] https://github.com/silverstripe/gha-tag-release/pull/1
- [x] https://github.com/silverstripe/gha-update-js/pull/1
- [x] https://github.com/silverstripe/gha-keepalive/pull/1

The following will be handled with https://github.com/silverstripe/gha-ci/issues/4:
- ~~https://github.com/silverstripe/silverstripe-assets/pull/496~~
- ~~https://github.com/silverstripe/silverstripe-framework/pull/10353~~
- ~~https://github.com/silverstripe/silverstripe-graphql/pull/472~~
- ~~https://github.com/silverstripe/silverstripe-graphql/pull/473~~

**Comment by ChloeSartorelli** [comment]
@emteknetnz Can you please add a meaningful description to each of the gha repositories? It will make it a lot easier to know at a glance what each repo is for.

**Comment by emteknetnz** [comment]
Descriptions are in the readme.md of each pull-request

**Comment by ChloeSartorelli** [comment]
6 months down the track, nobody will want to open each repo to remember, for example, the distinction between `gha-auto-tag` and `gha-tag-release` or what the purpose of `gha-pull-request` is. It's good practice to have a meaningful description for repositories.

**Comment by emteknetnz** [comment]
Oh, are you referring to text field in the actual github repo i.e.

![image](https://user-images.githubusercontent.com/4809037/171751528-4ca1d15f-0bc8-4c5a-aaaf-484c15c8dee8.png)
?

**Comment by ChloeSartorelli** [comment]
Yes, that's the one. Sorry, I should have been more explicit.

**Comment by emteknetnz** [comment]
Have added descriptions on the silverstripe account repos

**Comment by ChloeSartorelli** [comment]
@emteknetnz PRs merged. I think the next step is for you to create a `1` branch for each repo and create a PR that swaps from using `@main` to `@v1`
